name: Python linter
on: pull_request

jobs:
  python-linter:
    name: Python linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
